### ISSUE TITLE
Unable to change name of output file

### ISSUE THREAD

**Issue by andrewbrandwood** [cartridge/cartridge-sass#3]
# Project version: 
0.2.2

## Issue type: 
Bug

### Expected behaviour:
I should be able to change the name of the output css file. 
### Actual behaviour:
It only works currently with main.css

### Steps to reproduce the behaviour:
Try to change the name of the output src in the task.styles.js file.

**Comment by bmds** [comment]
Fixed the issue by updating the task.

**Comment by bmds** [comment]
Resolved in 0.2.3
