### ISSUE TITLE
Update ITCSS

### ISSUE THREAD

**Issue by furzeface** [cartridge/cartridge-sass#75]
As on [cartridge/issues/37](https://github.com/cartridge/cartridge/issues/37)

**Comment by daveaspinall** [comment]
Closing this issue since `elements` is correct.

See: https://github.com/itcss/itcss-netmag/tree/master/css

**Comment by furzeface** [comment]
Upto you, it seems they're interchangable 

https://youtu.be/1OKZOV-iLj4?t=32m13s
https://github.com/csswizardry/csswizardry.github.com/tree/master/css
https://speakerdeck.com/dafed/managing-css-projects-with-itcss

😉

**Comment by tawashley** [comment]
I do feel `elements` is more descriptive than `base`. It's almost implied that base means 'base elements'. Changing to base would also require a major semVer bump, due to config file changes. 👍
